---
- name: Install utilities
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Gdb
      ansible.builtin.apt:
        name: gdb
        state: present

    - name: Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Ansible
      ansible.builtin.apt:
        name: ansible-core
        state: present

    - name: Terraform
      community.general.snap:
        name: terraform
        state: present
        classic: true

    - name: Kubectl
      community.general.snap:
        name: kubectl
        state: present
        classic: true

    - name: Valgrind
      community.general.snap:
        name: valgrind
        state: present
        classic: true

    - name: Make
      ansible.builtin.apt:
        name: make
        state: present

    - name: Build essential
      ansible.builtin.apt:
        name: build-essential
        state: present

    - name: Cmake
      ansible.builtin.apt:
        name: cmake
        state: present

    - name: Gcc
      ansible.builtin.apt:
        name: gcc
        state: present

    - name: G++
      ansible.builtin.apt:
        name: g++
        state: present

    - name: Ninja build
      ansible.builtin.apt:
        name: ninja-build
        state: present

    - name: Netools
      ansible.builtin.apt:
        name: net-tools
        state: present

    - name: Neovim
      ansible.builtin.apt:
        name: neovim
        state: present

    - name: Policycoreutils
      ansible.builtin.apt:
        name: policycoreutils
        state: present

    - name: Gnupg2
      ansible.builtin.apt:
        name: gnupg2
        state: present
