---
- name: Install databases
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      changed_when: false

    - name: PostgreSQL and contrib packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present

    - name: Redis server
      apt:
        name: redis-server
        state: present

    - name: Duckdb
      community.general.snap:
        name: duckdb
        state: present
        classic: true
