---
- name: Install packages
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: PostgreSQL and contrib packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present

    - name: Redis server
      apt:
        name: redis-server
        state: present

    - name: Duckdb
      community.general.snap:
        name: duckdb
        state: present
        classic: yes
