---
- name: Install packages
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Go
      apt:
        name: golang-go
        state: present

    - name: rustup
      apt:
        name: rustup
        state: present

    - name: Rust stable toolchain
      become: no
      shell: "rustup toolchain install stable --profile minimal"
      args:
        creates: >-
          {{ ansible_env.HOME ~
          '/.rustup/toolchains/stable-x86_64-unknown-linux-gnu'}}

    - name: ruby
      apt:
        name: ruby
        state: present

    - name: lua
      apt:
        name: lua5.4
        state: present

    - name: uv
      community.general.snap:
        name: astral-uv
        state: present
        classic: yes

    - name: groovy
      community.general.snap:
        name: groovy
        state: present
        classic: yes

    - name: Add NodeSource setup script for Node.js 22
      shell: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash -

    - name: Install nodejs
      shell: sudo apt-get install -y nodejs
