---
- name: Install development tools
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      changed_when: false

    - name: OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Go
      apt:
        name: golang-go
        state: present

    - name: rustup
      apt:
        name: rustup
        state: present

    - name: Rust stable toolchain
      become: false
      shell: "rustup toolchain install stable --profile minimal"
      args:
        creates: >-
          {{ ansible_env.HOME ~
          '/.rustup/toolchains/stable-x86_64-unknown-linux-gnu'}}

    - name: ruby
      apt:
        name: ruby
        state: present

    - name: lua
      apt:
        name: lua5.4
        state: present

    - name: uv
      community.general.snap:
        name: astral-uv
        state: present
        classic: true

    - name: Add NodeSource setup script for Node.js 22
      shell: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash -

    - name: Install nodejs
      shell: sudo apt-get install -y nodejs

    - name: sdkman
      shell: curl -s "https://get.sdkman.io" | bash

    - name: groovy
      shell:
        cmd: . "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install groovy
        executable: /bin/bash
