---
- name: Install development tools
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: OpenJDK 17
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present

    - name: Go
      ansible.builtin.apt:
        name: golang-go
        state: present

    - name: Rustup
      ansible.builtin.apt:
        name: rustup
        state: present

    - name: Rust stable toolchain
      become: false
      ansible.builtin.shell: "rustup toolchain install stable --profile minimal"
      args:
        creates: >-
          {{ ansible_env.HOME ~
          '/.rustup/toolchains/stable-x86_64-unknown-linux-gnu'}}

    - name: Ruby
      ansible.builtin.apt:
        name: ruby
        state: present

    - name: Lua
      ansible.builtin.apt:
        name: lua5.4
        state: present

    - name: Python uv
      community.general.snap:
        name: astral-uv
        state: present
        classic: true

    - name: Add NodeSource setup script for Node.js 22
      ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash -

    - name: Install nodejs
      ansible.builtin.shell: sudo apt-get install -y nodejs

    - name: Sdkman
      ansible.builtin.shell: curl -s "https://get.sdkman.io" | bash

    - name: Groovy
      ansible.builtin.shell:
        cmd: . "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install groovy
        executable: /bin/bash
