---
- name: Install packages
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Go
      apt:
        name: golang-go
        state: present

    - name: Install rustup
      apt:
        name: rustup
        state: present

    - name: Install rust stable toolchain
      become: no
      shell: "rustup toolchain install stable --profile minimal"
      args:
        creates: "{{ ansible_env.HOME }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu"

    - name: Install gdb
      apt:
        name: gdb
        state: present
