---
- name: Install utilities
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      changed_when: false

    - name: Gdb
      apt:
        name: gdb
        state: present

    - name: Docker
      apt:
        name: docker.io
        state: present

    - name: Ansible
      apt:
        name: ansible-core
        state: present

    - name: Terraform
      community.general.snap:
        name: terraform
        state: present
        classic: true

    - name: Kubectl
      community.general.snap:
        name: kubectl
        state: present
        classic: true

    - name: Valgrind
      community.general.snap:
        name: valgrind
        state: present
        classic: true

    - name: Make
      apt:
        name: make
        state: present

    - name: Build essential
      apt:
        name: build-essential
        state: present

    - name: Cmake
      apt:
        name: cmake
        state: present

    - name: Gcc
      apt:
        name: gcc
        state: present

    - name: G++
      apt:
        name: g++
        state: present

    - name: Ninja build
      apt:
        name: ninja-build
        state: present

    - name: Netools
      apt:
        name: net-tools
        state: present

    - name: Neovim
      apt:
        name: neovim
        state: present

    - name: Firewall
      apt:
        name: firewalld
        state: present
