---
name: Ansible scripts CI

env:
  CI: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint *.yml
